/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controller.UserController;
import com.controller.dto.UserDTO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author hadt2
 */
public class LoginView extends javax.swing.JFrame {

    UserController uController = new UserController();
    private UserDTO currentUser;
//    MainMenu mainFrame;
    MainMenu mainMenu;

    /**
     * Creates new form LoginView
     *
     */
    public LoginView() {
        initComponents();
    }

    public LoginView(MainMenu mainMenu) {
        initComponents();
        this.mainMenu = mainMenu;
    }

    public UserDTO getCurrentUser() {
        return this.currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLoginName = new javax.swing.JTextField();
        txtLoginPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLoginName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtLoginName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 37));

        txtLoginPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginPassKeyPressed(evt);
            }
        });
        getContentPane().add(txtLoginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 37));

        jLabel2.setText("Tên đăng nhập:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 101, -1));

        jLabel3.setText("Mật khẩu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 85, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon("E:\\HocJava_DNU\\DictPharacy\\src\\main\\java\\com\\icon\\login1.png")); // NOI18N
        btnLogin.setText("  Đăng nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 130, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DICTIONARY MANAGER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\HocJava_DNU\\DictPharacy\\src\\main\\java\\com\\icon\\banner.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 480, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        UserDTO loginUser = uController.login(txtLoginName.getText(), String.valueOf(txtLoginPass.getPassword()));
        UserDTO checkUserName = uController.checkUserName(txtLoginName.getText());
        if (checkUserName != null) {
            currentUser = checkUserName;

            if (loginUser != null) {
                currentUser = loginUser;
                this.setVisible(false);
                mainMenu.setCurrentUser(currentUser);
                mainMenu.setVisible(true);

                //Tell user to change password if it was reset in the previous session
                if (String.valueOf(txtLoginPass.getPassword()).equals("abc123")) {
                    JOptionPane.showMessageDialog(null, "Mật khẩu của bạn đã được đặt lại, hay đổi mật khẩu khác.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                    mainMenu.btnSetting.doClick();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Mật khẩu không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tên đăng nhập không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        txtLoginName.grabFocus();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        txtLoginPass.setText("");   
    }//GEN-LAST:event_formWindowActivated

    private void txtLoginNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginNameKeyPressed
        // TODO add your handling code here:
        txtLoginName.grabFocus();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            UserDTO loginUser = uController.login(txtLoginName.getText(), String.valueOf(txtLoginPass.getPassword()));
            UserDTO checkUserName = uController.checkUserName(txtLoginName.getText());
            if (checkUserName != null) {
                currentUser = checkUserName;

                if (loginUser != null) {
                    currentUser = loginUser;
                    this.setVisible(false);
                    mainMenu.setCurrentUser(currentUser);
                    mainMenu.setVisible(true);

                    //Tell user to change password if it was reset in the previous session
                    if (String.valueOf(txtLoginPass.getPassword()).equals("abc123")) {
                        JOptionPane.showMessageDialog(null, "Mật khẩu của bạn đã được đặt lại, hay đổi mật khẩu khác.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                        mainMenu.btnSetting.doClick();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Mật khẩu không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    txtLoginName.grabFocus();
                }
                txtLoginPass.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtLoginNameKeyPressed

    private void txtLoginPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            UserDTO loginUser = uController.login(txtLoginName.getText(), String.valueOf(txtLoginPass.getPassword()));
            UserDTO checkUserName = uController.checkUserName(txtLoginName.getText());
            if (checkUserName != null) {
                currentUser = checkUserName;

                if (loginUser != null) {
                    currentUser = loginUser;
                    this.setVisible(false);
                    mainMenu.setCurrentUser(currentUser);
                    mainMenu.setVisible(true);

                    //Tell user to change password if it was reset in the previous session
                    if (String.valueOf(txtLoginPass.getPassword()).equals("abc123")) {
                        JOptionPane.showMessageDialog(null, "Mật khẩu của bạn đã được đặt lại, hay đổi mật khẩu khác.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                        mainMenu.btnSetting.doClick();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Mật khẩu không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
                txtLoginPass.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtLoginPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLoginName;
    private javax.swing.JPasswordField txtLoginPass;
    // End of variables declaration//GEN-END:variables
}
