/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

/**
 *
 * @author hadt2
 */
public class ManagerDictView extends javax.swing.JFrame {
    
    ManageEngDictView mngEngDict;
    ManageVieDictView mngVieDict;
    DefineVieDictView defineVieDict;
    DefineEngDictView defineEngDict;

    /**
     * Creates new form MainMenu
     */
    public ManagerDictView() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnhViet = new javax.swing.JButton();
        btnVietAnh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDefineEngVie = new javax.swing.JButton();
        btnDefineVieEng = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý từ điển");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAnhViet.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAnhViet.setIcon(new javax.swing.ImageIcon("E:\\HocJava_DNU\\DictPharacy\\src\\main\\java\\com\\icon\\eng.png")); // NOI18N
        btnAnhViet.setText("Anh - Việt");
        btnAnhViet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnhViet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnhViet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhVietActionPerformed(evt);
            }
        });

        btnVietAnh.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnVietAnh.setIcon(new javax.swing.ImageIcon("E:\\HocJava_DNU\\DictPharacy\\src\\main\\java\\com\\icon\\languages.png")); // NOI18N
        btnVietAnh.setText("Việt - Anh");
        btnVietAnh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVietAnh.setMaximumSize(new java.awt.Dimension(162, 54));
        btnVietAnh.setMinimumSize(new java.awt.Dimension(162, 54));
        btnVietAnh.setPreferredSize(new java.awt.Dimension(184, 54));
        btnVietAnh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVietAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVietAnhActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quản lý từ điển chuyên ngành dược");
        jPanel1.add(jLabel2);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGER DICTIONARY");
        jPanel2.add(jLabel1);

        btnDefineEngVie.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnDefineEngVie.setIcon(new javax.swing.ImageIcon("E:\\HocJava_DNU\\DictPharacy\\src\\main\\java\\com\\icon\\dictionary_define.png")); // NOI18N
        btnDefineEngVie.setText("Định nghĩa Anh-Việt");
        btnDefineEngVie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDefineEngVie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDefineEngVie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefineEngVieActionPerformed(evt);
            }
        });

        btnDefineVieEng.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnDefineVieEng.setIcon(new javax.swing.ImageIcon("E:\\HocJava_DNU\\DictPharacy\\src\\main\\java\\com\\icon\\dictionary_define.png")); // NOI18N
        btnDefineVieEng.setText("Định nghĩa Việt-Anh");
        btnDefineVieEng.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDefineVieEng.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDefineVieEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefineVieEngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDefineVieEng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVietAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDefineEngVie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnhViet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnVietAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAnhViet, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDefineEngVie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefineVieEng, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnAnhVietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhVietActionPerformed
        
        mngEngDict = new ManageEngDictView();
        mngEngDict.setVisible(true);
        mngEngDict.pack();
        mngEngDict.setLocationRelativeTo(null);
        mngEngDict.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnAnhVietActionPerformed

    private void btnVietAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVietAnhActionPerformed
        // TODO add your handling code here:
        mngVieDict = new ManageVieDictView();
        mngVieDict.setVisible(true);
        mngVieDict.pack();
        mngVieDict.setLocationRelativeTo(null);
        mngVieDict.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnVietAnhActionPerformed

    private void btnDefineEngVieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefineEngVieActionPerformed
        // TODO add your handling code here:
        defineEngDict = new DefineEngDictView();
        defineEngDict.setVisible(true);
        defineEngDict.setLocationRelativeTo(this);
        defineEngDict.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnDefineEngVieActionPerformed

    private void btnDefineVieEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefineVieEngActionPerformed
        // TODO add your handling code here:
        defineVieDict = new DefineVieDictView();
        defineVieDict.setVisible(true);
        defineVieDict.setLocationRelativeTo(this);
        defineVieDict.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnDefineVieEngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDictView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDictView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDictView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDictView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDictView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnhViet;
    private javax.swing.JButton btnDefineEngVie;
    private javax.swing.JButton btnDefineVieEng;
    private javax.swing.JButton btnVietAnh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
